package alex;
public enum ClaseLexica {
	ID, LIT_ENT, LIT_REAL, LIT_STRING, MAS, MENOS, AMP_DOBLE, MUL, DIV, PORCENTAJE,
	LT, GT, LTE, GTE, SAME, DIFF, PAP, PCIE, PC, ASIG, CCAP, CCCIE, LLAP, LLCIE, PUNTO,
	FLECHA, COMA, AMP, INT, REAL, BOOL, STRING, AND, OR, NOT, NULL, TRUE, FALSE, PROC, IF, THEN,
	ELSE, ENDIF, WHILE, DO, ENDWHILE, CALL, RECORD, ARRAY, OF, POINTER, NEW, DELETE, READ, WRITE, NL, VAR, TYPE, EOF
}
