
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 27 21:08:24 CEST 2022
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int LTE = 14;
  public static final int LLCIE = 25;
  public static final int LIT_REAL = 4;
  public static final int PC = 20;
  public static final int PORCENTAJE = 11;
  public static final int INT = 30;
  public static final int ARRAY = 50;
  public static final int WRITE = 56;
  public static final int DELETE = 54;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int LT = 12;
  public static final int RECORD = 49;
  public static final int TYPE = 59;
  public static final int LLAP = 24;
  public static final int OR = 35;
  public static final int BOOL = 32;
  public static final int CALL = 48;
  public static final int DIV = 10;
  public static final int IF = 41;
  public static final int ENDWHILE = 47;
  public static final int ID = 2;
  public static final int OF = 51;
  public static final int EOF = 0;
  public static final int ASIG = 21;
  public static final int AMP = 29;
  public static final int TRUE = 38;
  public static final int NEW = 53;
  public static final int error = 1;
  public static final int PCIE = 19;
  public static final int MUL = 9;
  public static final int COMA = 28;
  public static final int LIT_ENT = 3;
  public static final int LIT_STRING = 5;
  public static final int MENOS = 7;
  public static final int NULL = 37;
  public static final int AMP_DOBLE = 8;
  public static final int GTE = 15;
  public static final int REAL = 31;
  public static final int PAP = 18;
  public static final int CCAP = 22;
  public static final int FLECHA = 27;
  public static final int SAME = 16;
  public static final int ENDIF = 44;
  public static final int ELSE = 43;
  public static final int PUNTO = 26;
  public static final int NL = 57;
  public static final int READ = 55;
  public static final int WHILE = 45;
  public static final int THEN = 42;
  public static final int PROC = 40;
  public static final int CCCIE = 23;
  public static final int STRING = 33;
  public static final int DIFF = 17;
  public static final int POINTER = 52;
  public static final int FALSE = 39;
  public static final int GT = 13;
  public static final int VAR = 58;
  public static final int DO = 46;
  public static final int MAS = 6;
}

