/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int mas = 1;
  int menos = 2;
  int amp_doble = 3;
  int mul = 4;
  int div = 5;
  int porcentaje = 6;
  int lt = 7;
  int gt = 8;
  int lte = 9;
  int gte = 10;
  int same = 11;
  int diff = 12;
  int pap = 13;
  int pcie = 14;
  int pc = 15;
  int asig = 16;
  int ccap = 17;
  int ccie = 18;
  int llap = 19;
  int llcie = 20;
  int punto = 21;
  int flecha = 22;
  int coma = 23;
  int amp = 24;
  int int_t = 25;
  int real_t = 26;
  int bool_t = 27;
  int string_t = 28;
  int and = 29;
  int or = 30;
  int not = 31;
  int null_t = 32;
  int true_t = 33;
  int false_t = 34;
  int proc = 35;
  int if_t = 36;
  int then = 37;
  int else_t = 38;
  int endif = 39;
  int while_t = 40;
  int do_t = 41;
  int endwhile = 42;
  int call = 43;
  int record = 44;
  int array = 45;
  int of = 46;
  int pointer = 47;
  int new_t = 48;
  int delete = 49;
  int read = 50;
  int write = 51;
  int nl = 52;
  int var = 53;
  int type = 54;
  int eof = 55;
  int letra = 56;
  int digitoPositivo = 57;
  int digito = 58;
  int subrayado = 59;
  int parteEntera = 60;
  int parteDecimal = 61;
  int EXP = 62;
  int exponencial = 63;
  int ID = 66;
  int numeroEntero = 67;
  int numeroReal = 68;
  int litString = 69;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"&&\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"->\"",
    "\",\"",
    "\"&\"",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"string\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "\"$\"",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "\"_\"",
    "<parteEntera>",
    "<parteDecimal>",
    "<EXP>",
    "<exponencial>",
    "<token of kind 64>",
    "<token of kind 65>",
    "<ID>",
    "<numeroEntero>",
    "<numeroReal>",
    "<litString>",
  };

}
